name: Testes Agendados

on:
  schedule:
    - cron: '0 8 * * *' # Agendamento diário às 08:00 UTC
  workflow_dispatch:
    inputs:
      test-filter:
        description: 'Filtro de testes (Tag ou nome)'
        required: false
        default: 'regressive'
      filter-type:
        description: 'Tipo de filtro'
        required: true
        default: 'tag'
        type: choice
        options:
          - tag
          - test-name

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      STANDARD_USER: ${{ secrets.STANDARD_USER }}
      STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Rodar testes por tag
        if: github.event.inputs.filter-type == 'tag'
        run: mvn clean test -Dgroups=${{ github.event.inputs.test-filter }}

      - name: Rodar testes por nome
        if: github.event.inputs.filter-type == 'test-name'
        run: |
          TEST_FILTER="${{ github.event.inputs.test-filter }}"

          # se vazio ou valor padrão, executa tudo
          if [ -z "$TEST_FILTER" ] || [ "$TEST_FILTER" = "regressive" ]; then
            mvn clean test
          else
            # se contiver '.' assume FQCN, caso contrário envolve com curingas
            if [[ "$TEST_FILTER" == *.* ]]; then
              mvn -Dtest="$TEST_FILTER" clean test
            else
              mvn -Dtest="*$TEST_FILTER*" clean test
            fi
          fi

      - name: Gerar relatório Allure
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy relatório
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
